# Generated by Django 3.0.3 on 2020-02-27 23:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=10)),
                ('accountName', models.CharField(max_length=30)),
                ('currency', models.CharField(max_length=3)),
                ('accountOpeningDate', models.DateField()),
                ('lastTransactionDate', models.DateField()),
                ('accountType', models.CharField(max_length=30)),
                ('bvn', models.IntegerField()),
                ('fullname', models.CharField(max_length=30)),
                ('phoneNumber', models.BigIntegerField(blank=True)),
                ('email', models.CharField(blank=True, max_length=30)),
                ('status', models.CharField(choices=[('AC', 'active'), ('IN', 'inactive'), ('DO', 'dormant')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=10)),
                ('currency', models.CharField(max_length=3)),
                ('availableBalance', models.IntegerField()),
                ('clearedBalance', models.IntegerField(blank=True)),
                ('unclearBalance', models.IntegerField(blank=True)),
                ('holdBalance', models.IntegerField(blank=True)),
                ('minimumBalance', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountNumber', models.CharField(max_length=10)),
                ('amount', models.IntegerField()),
                ('currency', models.CharField(max_length=3)),
                ('channel', models.CharField(blank=True, max_length=10)),
                ('debitOrCredit', models.CharField(choices=[('Cr', 'Credit'), ('Dr', 'Debit')], max_length=2)),
                ('narration', models.TextField()),
                ('referenceId', models.UUIDField(default=uuid.uuid4)),
                ('transactionTime', models.DateTimeField()),
                ('transactionType', models.CharField(max_length=10)),
                ('valueDate', models.DateTimeField()),
                ('balanceAfter', models.IntegerField(blank=True)),
            ],
        ),
    ]
