# Generated by Django 3.0.3 on 2020-02-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balanceAfter',
            field=models.IntegerField(),
        ),
    ]
