# Generated by Django 3.0.3 on 2020-02-29 10:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200227_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionTime',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='valueDate',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
