# Generated by Django 3.0.3 on 2020-02-29 11:53

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200229_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='accountNumber',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='accountOpeningDate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='accountType',
            field=models.CharField(choices=[('SA', 'Savings'), ('CU', 'Current'), ('FD', 'Fixed Deposit')], max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='bvn',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='lastTransactionDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='availableBalance',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='clearedBalance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='holdBalance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='minimumBalance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='unclearBalance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=22),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.CharField(blank=True, choices=[('POS', 'POS'), ('ATM', 'ATM'), ('EC', 'E-Channels')], max_length=3),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='referenceId',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionTime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transactionType',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='valueDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
