# Generated by Django 3.0.3 on 2020-02-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200229_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerbalance',
            name='clearedBalance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='holdBalance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='minimumBalance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22),
        ),
        migrations.AlterField(
            model_name='customerbalance',
            name='unclearBalance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=22),
        ),
    ]
